package com.ydk.account.persistence.entity;

// Generated Feb 6, 2010 3:22:38 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.ydk.book.persistence.entity.Book;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "book_shelf", catalog = "ydk")
public class BookShelf implements java.io.Serializable {

	private Long id;
	private Reader reader;
	private Book book;

	public BookShelf() {
	}

	public BookShelf(Reader reader, Book book) {
		this.reader = reader;
		this.book = book;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reader")
	public Reader getReader() {
		return this.reader;
	}

	public void setReader(Reader reader) {
		this.reader = reader;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book")
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}
	
	
	@Transient
	public BookShelf setToPlainObject(BookShelf instance)
	{
		//Get self
		getId();
		BookShelf result = new BookShelf();
		
		result.cloneBookShelf(this);
		//Eager get @ManytoOne, @OnetoOne
		if (getReader() != null)
			result.setReader(getReader().setToPlainObjectQuick(getReader()));
		if (getBook() != null)
			result.setBook(getBook().setToPlainObjectQuick(getBook()));
		
		
		return result;
		

	}
	
	@Transient
	public BookShelf setToPlainObjectQuick(BookShelf instance)
	{
		//Get self
		getId();
		BookShelf result = new BookShelf();
		
		result.cloneBookShelf(this);

		//Eager get @ManytoOne, @OnetoOne
		result.setReader(null);
		
		result.setBook(null);
		
		
		return result;
	}
	
	public void cloneBookShelf(BookShelf instance) {
		id = instance.id;
		reader = instance.reader;
		book = instance.book;
	}

}
