package com.ydk.book.persistence.entity;

// Generated Jan 25, 2010 9:49:58 AM by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.JoinColumn;
import javax.persistence.TableGenerator;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;
import org.springframework.core.style.ToStringCreator;
import org.springframework.transaction.annotation.Transactional;
import com.ydk.account.persistence.entity.*;



/**
 * Owners generated by hbm2java
 */
@Entity
@Table(name = "book_review", catalog = "ydk")
public class BookReview extends Subject implements java.io.Serializable {


	private Long author;
	private String source;
	private String editor;
	private String type;
	private String content;
	private Boolean isQa;
	
	private BookReviewCategory bookReviewCategory;

	public BookReview() {
		super();
		this.subjectType = this.SUBJECT_TYPE_BOOKREVIEW;
	}
	
	public BookReview(String title, Date date) {
		super();
		this.title = title;
		this.subjectType = this.SUBJECT_TYPE_BOOKREVIEW;
		this.date = date;
	}
	
	public BookReview(Long id, String title, String subjectType, Date date,
			Integer order, Boolean isNew, Boolean recommanded, Boolean visible,
			String introduction, String titleImage, ArrayList<String> images,
			Book book, Long author, String source, String editor, String type,
			String content, Boolean isQa, BookReviewCategory bookReviewCategory) {
		this.id = id;
		this.title = title;
		this.subjectType = subjectType;
		this.date = date;
		this.order = order;
		this.isNew = isNew;
		this.recommanded = recommanded;
		this.visible = visible;
		this.introduction = introduction;
		this.titleImage = titleImage;
		this.images = images;
		this.book = book;
		this.author = author;
		this.source = source;
		this.editor = editor;
		this.type = type;
		this.content = content;
		this.isQa = isQa;
		this.bookReviewCategory = bookReviewCategory;
	}

	@Column(name = "author")
	public Long getAuthor() {
		return this.author;
	}
	public void setAuthor(Long author) {
		this.author = author;
	}
	
	@Column(name = "source")
	public String getSource() {
		return this.source;
	}
	public void setSource(String source) {
		this.source = source;
	}
	
	@Column(name = "editor")
	public String getEditor() {
		return this.editor;
	}
	public void setEditor(String editor) {
		this.editor = editor;
	}
	
	@Column(name = "type")
	public String getType() {
		return this.type;
	}
	public void setType(String type) {
		this.type = type;
	}
	
	@Column(name = "content")
	public String getContent() {
		return this.content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	
	@Column(name = "isQa")
	public Boolean getIsQa() {
		return this.isQa;
	}
	public void setIsQa(Boolean isQa) {
		this.isQa = isQa;
	}
	
//	@OneToOne(cascade= CascadeType.ALL, fetch = FetchType.LAZY)
//	@JoinTable(name = "book_reviews_title_img",
//        joinColumns = 
//        	@JoinColumn(name="subject_id"),
//        inverseJoinColumns = 
//        	@JoinColumn(name="image_id")
//    )
//	public FileDescriptor getTitleImage() {
//		return titleImage;
//	}
//	public void setTitleImage(FileDescriptor titleImage) {
//		this.titleImage = titleImage;
//	}
	
	
//	@OneToMany(fetch = FetchType.LAZY, 
//			cascade = {CascadeType.PERSIST, CascadeType.REMOVE})
//    @JoinTable(
//            name="book_reviews_images",
//            joinColumns = @JoinColumn( name="subject_id"),
//            inverseJoinColumns = @JoinColumn( name="image_id")
//    )
//    public List<FileDescriptor> getImages()
//    {
//		return this.images;
//    }
//	public void setImages(List<FileDescriptor> images) {
//		this.images = images;
//	}
	
	@ManyToOne(fetch = FetchType.LAZY, 
			cascade = {CascadeType.PERSIST})
	@JoinTable(
            name="book_book_reviews",
            joinColumns = @JoinColumn( name="subject_pk"),
            inverseJoinColumns = @JoinColumn( name="book_pk")
    )
	public Book getBook() {
		return this.book;
	}
	public void setBook(Book book) {
		this.book = book;
	}

	/**
	 * @return the bookReviewCategory
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book_review_category", nullable = false)
	public BookReviewCategory getBookReviewCategory() {
		return bookReviewCategory;
	}
	public void setBookReviewCategory(BookReviewCategory bookReviewCategory) {
		this.bookReviewCategory = bookReviewCategory;
	}
	
	@Transient
	public BookReview setToPlainObject(BookReview instance)
	{
		//Get self
		getTitle();
		BookReview result = new BookReview();
		result.cloneInstance(this);
		//Eager get @ManytoOne, @OnetoOne
		if (getBook() != null)
		{
			result.setBook(
					getBook().setToPlainObjectQuick(getBook()));
		}
		
		result.setBookReviewCategory(
				getBookReviewCategory().setToPlainObject(getBookReviewCategory()));
		
//		setTitleImage(
//				getTitleImage().setToPlainObjectQuick(getTitleImage()));
		

		//Null oneToMany;
//		setImages(null);
		

		return result;
	}
	
	@Transient
	public BookReview setToPlainObjectQuick(BookReview instance)
	{
		//Get self
		getTitle();
		BookReview result = new BookReview();
		result.cloneInstance(this);
		//Eager get @ManytoOne, @OnetoOne
		result.setBook(null);
		
		result.setBookReviewCategory(
				result.getBookReviewCategory().setToPlainObject(result.getBookReviewCategory()));
		
//		setTitleImage(null);
		
		//Null oneToMany;
//		setImages(null);
		

		return result;
	}
	
	public void cloneInstance(BookReview instance) {
		id = instance.id;
		title = instance.title;
		subjectType = instance.subjectType;
		date = instance.date;
		order = instance.order;
		isNew = instance.isNew;
		recommanded = instance.recommanded;
		visible = instance.visible;
		introduction = instance.introduction;
		titleImage = instance.titleImage;
		images = instance.images;
		book = instance.book;
		author = instance.author;
		source = instance.source;
		editor = instance.editor;
		type = instance.type;
		content = instance.content;
		isQa = instance.isQa;
		bookReviewCategory = instance.bookReviewCategory;
	}
	
	
}
