package com.ydk.book.persistence.entity;

// Generated Jan 25, 2010 9:49:58 AM by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.JoinColumn;
import javax.persistence.TableGenerator;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;
import org.springframework.core.style.ToStringCreator;
import org.springframework.transaction.annotation.Transactional;
import com.ydk.account.persistence.entity.*;



/**
 * Owners generated by hbm2java
 */
@Entity
@Table(name = "book_news", catalog = "ydk")
public class BookNews extends Subject implements java.io.Serializable {


	private Long author;
	private Long source;
	private Long editor;
	private String type;
	private String content;
	
	private BookNewsCategory bookNewsCategory;

	public BookNews() {
		super();
		this.subjectType = this.SUBJECT_TYPE_BOOKNEWS;
	}
	
	public BookNews(String title, String interviewer, Date date) {
		this.title = title;
		this.subjectType = this.SUBJECT_TYPE_BOOKNEWS;
		this.date = date;
	}
	
	
	
	public BookNews(String title, String subjectType, Date date,
			Integer order, Boolean isNew, Boolean recommanded, Boolean visible,
			String introduction, String titleImage, ArrayList<String> images,
			Book book, Long author, Long source, Long editor, String type,
			String content, BookNewsCategory bookNewsCategory) {
		this.title = title;
		this.subjectType = subjectType;
		this.date = date;
		this.order = order;
		this.isNew = isNew;
		this.recommanded = recommanded;
		this.visible = visible;
		this.introduction = introduction;
		this.titleImage = titleImage;
		this.images = images;
		this.book = book;
		this.author = author;
		this.source = source;
		this.editor = editor;
		this.type = type;
		this.content = content;
		this.bookNewsCategory = bookNewsCategory;
	}

	@Column(name = "source")
	public Long getSource() {
		return this.source;
	}
	public void setSource(Long source) {
		this.source = source;
	}
	
	@Column(name = "author")
	public Long getAuthor() {
		return this.author;
	}
	public void setAuthor(Long author) {
		this.author = author;
	}
	
	@Column(name = "editor")
	public Long getEditor() {
		return this.editor;
	}
	public void setEditor(Long editor) {
		this.editor = editor;
	}
	
	@Column(name = "type")
	public String getType() {
		return this.type;
	}
	public void setType(String type) {
		this.type = type;
	}
	
	@Column(name = "content")
	public String getContent() {
		return this.content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	
	
//	@OneToOne(cascade= CascadeType.ALL, fetch = FetchType.LAZY)
//	@JoinTable(name = "book_news_title_img",
//        joinColumns = 
//        	@JoinColumn(name="subject_id"),
//        inverseJoinColumns = 
//        	@JoinColumn(name="image_id")
//    )
//	public FileDescriptor getTitleImage() {
//		return titleImage;
//	}
//	public void setTitleImage(FileDescriptor titleImage) {
//		this.titleImage = titleImage;
//	}
	
	
//	@OneToMany(fetch = FetchType.LAZY, 
//			cascade = {CascadeType.ALL, CascadeType.REMOVE})
//    @JoinTable(
//            name="book_news_images",
//            joinColumns = @JoinColumn( name="subject_id"),
//            inverseJoinColumns = @JoinColumn( name="image_id")
//    )
//    public List<FileDescriptor> getImages()
//    {
//		return this.images;
//    }
//	public void setImages(List<FileDescriptor> images) {
//		this.images = images;
//	}
	
	@ManyToOne(fetch = FetchType.LAZY, 
			cascade = {CascadeType.PERSIST})
	@JoinTable(
            name="book_book_news",
            joinColumns = @JoinColumn( name="subject_pk"),
            inverseJoinColumns = @JoinColumn( name="book_pk")
    )
	public Book getBook() {
		return this.book;
	}
	public void setBook(Book book) {
		this.book = book;
	}

	

	/**
	 * @return the eventCategory
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book_news_category", nullable = false)
	public BookNewsCategory getBookNewsCategory() {
		return bookNewsCategory;
	}
	public void setBookNewsCategory(BookNewsCategory bookNewsCategory) {
		this.bookNewsCategory = bookNewsCategory;
	}
	
	@Transient
	public BookNews setToPlainObject(BookNews instance)
	{
		//Get self
		getTitle();
		BookNews result = new BookNews();
		result.cloneInstance(this);
		//Eager get @ManytoOne, @OnetoOne
		if (result.getBook() != null)
		{
			result.setBook(
					result.getBook().setToPlainObjectQuick(result.getBook()));
		}
		
		result.setBookNewsCategory(
				result.getBookNewsCategory().setToPlainObject(result.getBookNewsCategory()));
		
//		setTitleImage(
//				getTitleImage().setToPlainObjectQuick(getTitleImage()));
		
				
		//Null oneToMany;
//		setImages(null);
		

		return result;
	}
	
	@Transient
	public BookNews setToPlainObjectQuick(BookNews instance)
	{
		//Get self
		getTitle();
		BookNews result = new BookNews();
		result.cloneInstance(this);
		//Eager get @ManytoOne, @OnetoOne
		result.setBook(null);
		
		
		result.setBookNewsCategory(
				getBookNewsCategory().setToPlainObject(getBookNewsCategory()));
		
//		setTitleImage(null);
		
		//Null oneToMany;
//		setImages(null);
		

		return result;
	}
	
	public void cloneInstance(BookNews instance) {
		id = instance.id;
		title = instance.title;
		subjectType = instance.subjectType;
		date = instance.date;
		order = instance.order;
		isNew = instance.isNew;
		recommanded = instance.recommanded;
		visible = instance.visible;
		introduction = instance.introduction;
		titleImage = instance.titleImage;
		images = instance.images;
		book = instance.book;
		author = instance.author;
		source = instance.source;
		editor = instance.editor;
		type = instance.type;
		content = instance.content;
		bookNewsCategory = instance.bookNewsCategory;
	}
	
}
