package com.ydk.book.persistence.entity;

// Generated Jan 25, 2010 9:49:58 AM by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.JoinColumn;
import javax.persistence.TableGenerator;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;
import org.springframework.core.style.ToStringCreator;
import org.springframework.transaction.annotation.Transactional;
import com.ydk.account.persistence.entity.*;



/**
 * Owners generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "ydk")
public class Event extends Subject implements java.io.Serializable {

	private String location;
	private String content;
	
	private EventCategory eventCategory;

	public Event() {
		super();
		this.subjectType = this.SUBJECT_TYPE_EVENT;
	}
	
	public Event(String title, String location, Date date) {
		super();
		this.title = title;
		this.location = location;
		this.subjectType = this.SUBJECT_TYPE_EVENT;
		this.date = date;
	}
	
	
	/**
	 * @param location
	 * @param content
	 * @param eventCategory
	 */
	public Event(Long id, String title, String subjectType, Date date,
			Integer order, Boolean isNew, Boolean recommanded, Boolean visible,
			String introduction, String titleImage, ArrayList<String> images,
			Book book, String location, String content, EventCategory eventCategory) {
		this.id = id;
		this.title = title;
		this.subjectType = subjectType;
		this.date = date;
		this.order = order;
		this.isNew = isNew;
		this.recommanded = recommanded;
		this.visible = visible;
		this.introduction = introduction;
		this.titleImage = titleImage;
		this.images = images;
		this.book = book;
		this.location = location;
		this.content = content;
		this.eventCategory = eventCategory;
	}

	@Column(name = "location")
	public String getLocation() {
		return this.location;
	}
	public void setLocation(String location) {
		this.location = location;
	}
	
	@Column(name = "content")
	public String getContent() {
		return this.content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	
//	@OneToOne(cascade= CascadeType.ALL, fetch = FetchType.LAZY)
//	@JoinTable(name = "event_title_img",
//        joinColumns = 
//        	@JoinColumn(name="subject_id"),
//        inverseJoinColumns = 
//        	@JoinColumn(name="image_id")
//    )
//	public FileDescriptor getTitleImage() {
//		return titleImage;
//	}
//	public void setTitleImage(FileDescriptor titleImage) {
//		this.titleImage = titleImage;
//	}
	
	
//	@OneToMany(fetch = FetchType.LAZY, 
//			cascade = {CascadeType.PERSIST, CascadeType.REMOVE})
//    @JoinTable(
//            name="event_images",
//            joinColumns = @JoinColumn( name="subject_id"),
//            inverseJoinColumns = @JoinColumn( name="image_id")
//    )
//    public List<FileDescriptor> getImages()
//    {
//		return this.images;
//    }
//	public void setImages(List<FileDescriptor> images) {
//		this.images = images;
//	}
	
	@ManyToOne(fetch = FetchType.LAZY, 
			cascade = {CascadeType.PERSIST})
	@JoinTable(
            name="book_events",
            joinColumns = @JoinColumn( name="subject_pk"),
            inverseJoinColumns = @JoinColumn( name="book_pk")
    )
	public Book getBook() {
		return this.book;
	}
	public void setBook(Book book) {
		this.book = book;
	}

	/**
	 * @return the eventCategory
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "event_category", nullable = false)
	public EventCategory getEventCategory() {
		return eventCategory;
	}
	public void setEventCategory(EventCategory eventCategory) {
		this.eventCategory = eventCategory;
	}
	
	@Transient
	public Event setToPlainObject(Event instance)
	{
		//Get self
		getTitle();
		
		Event result = new Event();
		result.cloneInstance(this);
		//Eager get @ManytoOne, @OnetoOne
		if (getBook() != null)
		{
			result.setBook(
					getBook().setToPlainObjectQuick(getBook()));
		}
		
		result.setEventCategory(
				getEventCategory().setToPlainObject(getEventCategory()));
		
//		setTitleImage(
//				getTitleImage().setToPlainObjectQuick(getTitleImage()));
		
				
		//Null oneToMany;
//		setImages(null);
		
		return result;
	}
	
	@Transient
	public Event setToPlainObjectQuick(Event instance)
	{
		//Get self
		getTitle();
		
		Event result = new Event();
		result.cloneInstance(this);
		//Eager get @ManytoOne, @OnetoOne
		result.setBook(null);
		
		result.setEventCategory(
				result.getEventCategory().setToPlainObject(result.getEventCategory()));
		
//		setTitleImage(null);
		
		//Null oneToMany;
//		setImages(null);
		
		return result;
	}
	
	public void cloneInstance(Event instance) {
		id = instance.id;
		title = instance.title;
		subjectType = instance.subjectType;
		date = instance.date;
		order = instance.order;
		isNew = instance.isNew;
		recommanded = instance.recommanded;
		visible = instance.visible;
		introduction = instance.introduction;
		titleImage = instance.titleImage;
		images = instance.images;
		book = instance.book;
		location = instance.location;
		content = instance.content;
		eventCategory = instance.eventCategory;
	}
	
	
}
