package com.ydk.account.persistence.entity;

// Generated Feb 6, 2010 2:13:01 PM by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "ydk")
public class Address implements java.io.Serializable {

	private Long id;
	private String country;
	private String state;
	private String city;
	private String district;
	private String street;
	private String location;
	private String postCode;
	private List<Reader> readers = new ArrayList<Reader>(0);

	public Address() {
	}

	public Address(String country, String state, String city, String district,
			String street, String location, String postCode, List<Reader> readers) {
		this.country = country;
		this.state = state;
		this.city = city;
		this.district = district;
		this.street = street;
		this.location = location;
		this.postCode = postCode;
		this.readers = readers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "country")
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "district")
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "street")
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "location")
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "post_code")
	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public List<Reader> getReaders() {
		return this.readers;
	}

	public void setReaders(List<Reader> readers) {
		this.readers = readers;
	}
	
	@Transient
	public Address setToPlainObject(Address instance)
	{
		//Get self
		instance.getCountry();
		//Eager get @ManytoOne, @OnetoOne
		//Null oneToMany;
		instance.setReaders(null);

		return instance;
	}
	@Transient
	public Address setToPlainObjectQuick(Address instance)
	{
		//Get self
		instance.getCountry();
		//Eager get @ManytoOne, @OnetoOne
		//Null oneToMany;
		instance.setReaders(null);

		return instance;
	}

}
