package com.ydk.account.persistence.entity;

// Generated Feb 6, 2010 2:13:01 PM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PartnerType generated by hbm2java
 */
@Entity
@Table(name = "partner_type", catalog = "ydk")
public class PartnerType implements java.io.Serializable {

	private Long id;
	private String type;
	private List<Partner> partners = new ArrayList<Partner>(0);

	public PartnerType() {
	}
	
	public PartnerType(Long id) {
		this.id = id;
	}
	
	public PartnerType(String type) {
		this.type = type;
	}

	public PartnerType(String type, List<Partner> partners) {
		this.type = type;
		this.partners = partners;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}
	public void setId(Long id) {
		this.id = id;
	}

	
	
	@Column(name = "type", unique = true, nullable = false, length = 50)
	public String getType() {
		return this.type;
	}
	public void setType(String type) {
		this.type = type;
	}

	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partnerType", cascade = {CascadeType.REMOVE})
	public List<Partner> getPartners() {
		return this.partners;
	}

	public void setPartners(List<Partner> partners) {
		this.partners = partners;
	}

}
