package com.ydk.account.persistence.entity;

// Generated Feb 6, 2010 2:13:01 PM by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PartnerType generated by hbm2java
 */
@Entity
@Table(name = "resource_type", catalog = "ydk")
public class ResourceType implements java.io.Serializable {

	public static final String RESOURCETYPE_BOOK = "Book";
	public static final String RESOURCETYPE_EVENT = "Event";
	public static final String RESOURCETYPE_BOOKNEWS = "BookNews";
	public static final String RESOURCETYPE_BOOKREVIEW = "BookReview";
	public static final String RESOURCETYPE_INTERVIEW = "Interview";
	
	
	private String type;
	//TODO Here should be a base class Resource
//	private List<Resource> partners = new ArrayList<Resource>(0);

	public ResourceType() {
	}

	public ResourceType(String type) {
		this.type = type;
	}


	@Id
	@Column(name = "type", unique = true, nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
